from config.config import get_config
from utils.prompts import DEFAULT_SYSTEM_PROMPT, DEFAULT_USER_PROMPT, DEFAULT_REFINE_PROMPT

cfg = get_config('config/config.yaml')
cfg.merge_from_file('config/postgres.yaml')


STREAM = cfg.MODEL.STREAM
SERVICE = cfg.MODEL.SERVICE
TEMPERATURE = cfg.MODEL.TEMPERATURE
MODEL_ID = cfg.MODEL.MODEL_ID


# Embeddings
EMBEDDING_SERVICE = cfg.MODEL.EMBEDDING_SERVICE
EMBEDDING_MODEL_NAME = cfg.MODEL.EMBEDDING_MODEL_NAME 

DOCUMENT_EMBEDDING_MODEL_NAME = cfg.MODEL.DOCUMENT_EMBEDDING_MODEL_NAME
DOCUMENT_EMBEDDING_SERVICE = cfg.MODEL.DOCUMENT_EMBEDDING_SERVICE
# Prompts
SYSTEM_PROMPT = DEFAULT_SYSTEM_PROMPT
USER_PROMPT = DEFAULT_USER_PROMPT
REFINE_PROMPT = DEFAULT_REFINE_PROMPT

